#!/bin/sh
set -e
[ "${IPKG_NO_SCRIPT:-}" = 1 ] && exit 0
[ -n "${IPKG_INSTROOT:-}" ] && exit 0
# @STOP_UTILITIES@
minscale_remember_service
[ ! -x /etc/init.d/tailscale ] || /etc/init.d/tailscale stop
minscale_wait_service
minscale_detach_image
[ ! -x /etc/init.d/minscale-bin ] || /etc/init.d/minscale-bin disable
